server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.43.139:8848  # 修改本机的host文件即可
    gateway:
      discovery:
        locator:
          enabled: true  # 启用gateway 服务发现功能
          lower-case-service-id: true  # 启用小驼峰的服务名称访问服务
      routes: # 自定义路由机制
        - id: admin-service-router   # 后台管理系统
          uri: lb://admin-service   # 转发到那个目的地
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1 # 当前端访问/admin/login - >login 将admin自动的去掉
        - id: member-service-router  # 会员服务
          uri: lb://member-service
          predicates:
            - Path=/member/**
          filters:
            - StripPrefix=1 # 当前端访问/member/xxx - >xxx 将member自动的去掉
        - id: finance-service-router  # 清算服务
          uri: lb://finance-service
          predicates:
            - Path=/finance/**
          filters:
            - StripPrefix=1
        - id: chan-service-router    # 推送服务
          uri: lb://chan-service
          predicates:
            - Path=/achan/**
          filters:
            - StripPrefix=1
        - id: match-service-router   #  撮合服务
          uri: lb://match-service
          predicates:
            - Path=/match/**
          filters:
            - StripPrefix=1
        - id: exchange-service-router  # 在线交易服务
          uri: lb://exchange-service
          predicates:
            - Path=/exchange/**
          filters:
            - StripPrefix=1
    # 通过网关来完成 对2种维度的限流：网关维度+API分组
    sentinel:
      transport:
        dashboard: 127.0.0.1:8090
      filter:
        enabled: true
      datasource:
        ds1.nacos: #com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource 使用Nacos持久化我的sentinel 数据时，需要添加nacos-datasource的依赖
          server-addr: 192.168.43.139:8848
          data-id: gw-flow
          rule-type: gw_flow   # 规则类型
        ds2.nacos:
          server-addr: 192.168.43.139:8848
          data-id: api-group
          rule-type: gw_api_group   # 规则类型

redis:
  host: 47.108.239.87
  port: 6379